---
- name: Update packages
  hosts: all
  become: true

  tasks:
    - name: Update installed packages
      ansible.builtin.package:
        name: '*'
        state: latest
      register: is_updated
    
    - name: Reboot the system
      ansible.builtin.reboot:
      when: is_updated.changed
